services:
  scdl:
    build: .
    container_name: soundcloud-downloader
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads
    logging:
      options:
        max-size: "10m"
        max-file: "3"
